### ISSUE TITLE
Breaks sitemap.xml

### ISSUE THREAD

**Issue by jnaskali** [sourcesoldier/grav-plugin-tidyhtml#2]
Strips xml from the sitemap generated by [sitemap plugin](https://github.com/getgrav/grav-plugin-sitemap), breaking the output.

I'll see if I can modify the code to accept a list of ignored routes.

**Comment by sourcesoldier** [comment]
@jnaskali Thanks for your contribution. I've updated the code and extracted some of that into a new method.
